spring.datasource.url=jdbc:h2:mem:allergydb;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE

spring.h2.console.enabled=true

scheduler.cron=-
scheduler.weekly-cron=-

telegram.bot-token=local-dummy
telegram.chat-id=0
